###
POST http://127.0.0.1:5000/api/users/register
Accept: application/json
Content-Type: application/json

{
  "name":"user",
  "email":"rtolinggi91@gmail.com",
  "password":"password",
  "confirmPassword":"password"
}

###
GET http://127.0.0.1:5000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjE2ZGJjYjc2OWExMmIzYzI2ODA1ZSIsImlhdCI6MTY0NjM1ODEzOCwiZXhwIjoxNjQ2MzU4MTU4fQ.bXFUYEGpCVOA9ww_m8ezcC6ngQwTsttQ-C6droRgMQM

###
POST  http://127.0.0.1:5000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email":"rtolinggi91@gmail.com",
  "password":"password"
}

###
GET http://127.0.0.1:5000/api/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjE2ZGJjYjc2OWExMmIzYzI2ODA1ZSIsImlhdCI6MTY1MDQzOTU4NywiZXhwIjoxNjUwNDM5NjA3fQ.moxJuGKMgduc9OIvvCfP7zwMhbrbyRKAgDxd3qVjxdk
###
GET http://127.0.0.1:5000/api/karyawan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjE2ZGJjYjc2OWExMmIzYzI2ODA1ZSIsImlhdCI6MTY1MDQzOTYxNSwiZXhwIjoxNjUwNDM5NjM1fQ.SpkgdDJhF1_cy3Sqsq-50yvBI2Ay-rwyvdoouGkV9zA


###
GET http://127.0.0.1:5000/api/users/token

###
DELETE http://127.0.0.1:5000/api/users/logout

###
PUT http://127.0.0.1:5000/api/users/forgotpassword
Accept: application/json
Content-Type: application/json

{
  "email":"rtolinggi91@gmail.com"
}

###
POST  http://127.0.0.1:5000/api/karyawan
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGE5NTQ5ZTIzNDk0NzdmMTRjMGRiOCIsImlhdCI6MTY0OTA1Nzk0MSwiZXhwIjoxNjQ5MDU3OTYxfQ.ePbv9xp0cijKjZgGr68Xj_sRdW9xUbeAS7Jovg9Zk0c

{
  "name":"Stevi Hebel Mait",
  "nik":95364,
  "position":"Coordinator I",
  "active":true,
  "noContact":"081351441899"
}

###
DELETE  http://127.0.0.1:5000/api/karyawan/624bbd20fd38232daa5858d4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGE5NTQ5ZTIzNDk0NzdmMTRjMGRiOCIsImlhdCI6MTY0OTE0NDI3MywiZXhwIjoxNjQ5MTQ0MjkzfQ.gX26sNhyMkVH-QTGNOERoa8Y2IKbSomE5aipZ84jZQ4

###
PUT  http://127.0.0.1:5000/api/karyawan/6241612671edfd092b451347
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGE5NTQ5ZTIzNDk0NzdmMTRjMGRiOCIsImlhdCI6MTY0OTA1NzkxMSwiZXhwIjoxNjQ5MDU3OTMxfQ.p9_3vPCbJ87yuPZJtuVX-l3aD3tyjbbarWmYLrcls3c

{
  "name":"Stevi Mait",
  "nik":95364,
  "position":"Coordinator I",
  "active":true,
  "noContact":"081351441899"
}