###
POST http://127.0.0.1:5000/api/users/register
Accept: application/json
Content-Type: application/json

{
  "name":"user",
  "email":"rtolinggi91@gmail.com",
  "password":"password",
  "confirmPassword":"password"
}

###
GET http://127.0.0.1:5000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjE2ZGJjYjc2OWExMmIzYzI2ODA1ZSIsImlhdCI6MTY0NjM1ODEzOCwiZXhwIjoxNjQ2MzU4MTU4fQ.bXFUYEGpCVOA9ww_m8ezcC6ngQwTsttQ-C6droRgMQM

###
POST  http://127.0.0.1:5000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email":"rtolinggi91@gmail.com",
  "password":"password"
}

###
GET http://127.0.0.1:5000/api/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjE2ZGJjYjc2OWExMmIzYzI2ODA1ZSIsImlhdCI6MTY0Njc1NzEwOCwiZXhwIjoxNjQ2NzU3MTI4fQ.A0u8uSFfwOYRMyhvadtroqh7dTQ_4Q33SJYDPTrWbkM

###
GET http://127.0.0.1:5000/api/karyawan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGE5NTQ5ZTIzNDk0NzdmMTRjMGRiOCIsImlhdCI6MTY0OTEyNjE5MSwiZXhwIjoxNjQ5MTI2MjExfQ.pDWSbe_6IX4V9CMCE-vIzHCTbEUYXEZYWweOP095vPE


###
GET http://127.0.0.1:5000/api/users/token

###
DELETE http://127.0.0.1:5000/api/users/logout

###
PUT http://127.0.0.1:5000/api/users/forgotpassword
Accept: application/json
Content-Type: application/json

{
  "email":"rtolinggi91@gmail.com"
}

###
POST  http://127.0.0.1:5000/api/karyawan
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGE5NTQ5ZTIzNDk0NzdmMTRjMGRiOCIsImlhdCI6MTY0OTA1Nzk0MSwiZXhwIjoxNjQ5MDU3OTYxfQ.ePbv9xp0cijKjZgGr68Xj_sRdW9xUbeAS7Jovg9Zk0c

{
  "name":"Stevi Hebel Mait",
  "nik":95364,
  "position":"Coordinator I",
  "active":true,
  "noContact":"081351441899"
}

###
DELETE  http://127.0.0.1:5000/api/karyawan/6241612671edfd092b451347
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmVmOTdhOTdmMGMyNjFkMjlmZjEzNSIsImlhdCI6MTY0ODQ1Mjc2MiwiZXhwIjoxNjQ4NDUyNzgyfQ.jwLpMbzroVROXs96BSC-fL0zWT1D8uOMxfqh_Ymg9hw

###
PUT  http://127.0.0.1:5000/api/karyawan/6241612671edfd092b451347
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGE5NTQ5ZTIzNDk0NzdmMTRjMGRiOCIsImlhdCI6MTY0OTA1NzkxMSwiZXhwIjoxNjQ5MDU3OTMxfQ.p9_3vPCbJ87yuPZJtuVX-l3aD3tyjbbarWmYLrcls3c

{
  "name":"Stevi Mait",
  "nik":95364,
  "position":"Coordinator I",
  "active":true,
  "noContact":"081351441899"
}